package com.example.util

import androidx.compose.runtime.staticCompositionLocalOf

data class LanguageItem(
    val code: String,
    val name: String,
    val flag: String
)

val SUPPORTED_LANGUAGES = listOf(
    LanguageItem("es", "Español", "🇪🇸"),
    LanguageItem("en", "English", "🇺🇸"),
    LanguageItem("fr", "Français", "🇫🇷"),
    LanguageItem("pt", "Português", "🇧🇷"),
    LanguageItem("de", "Deutsch", "🇩🇪"),
    LanguageItem("it", "Italiano", "🇮🇹")
)

data class AppTranslations(
    // App Bar & Global
    val appName: String,
    val menu: String,
    val newChat: String,
    val close: String,
    val delete: String,
    val cancel: String,
    val yes: String,
    val notNow: String,
    val remindMe: String,
    val ignore: String,
    val today: String,
    val yesterday: String,
    val previousDays: String,

    // Tools & Quick Features
    val toolsHeader: String,
    val cameraLens: String,
    val shoppingList: String,
    val docTools: String,
    val webBrowser: String,
    val tasks: String,
    val modes: String,
    val changeMode: String,

    // Drawer & History
    val noChats: String,
    val clearHistory: String,
    val deleteChatDialogTitle: String,
    val deleteChatConfirm: String,
    val clearAllChatsDialogTitle: String,
    val clearAllChatsConfirm: String,
    val clearAllChatsConfirmBtn: String,

    // Chat Area & Input
    val quickSuggestions: String,
    val chatPlaceholder: String,
    val send: String,
    val sendAudio: String,
    val dictate: String,
    val speechPrompt: String,
    val recordingVoice: String,
    val cancelRecording: String,

    // Settings
    val settingsTitle: String,
    val settingsSubtitle: String,
    val languageSection: String,
    val languageSubtitle: String,
    val modelsButton: String,
    val modelsSubtitle: String,
    val appearanceSection: String,
    val appearanceSubtitle: String,
    val darkMode: String,
    val lightMode: String,
    val systemMode: String,
    val voiceTypeSection: String,
    val voiceTypeSubtitle: String,
    val femaleVoice: String,
    val maleVoice: String,
    val dailyQuotaTitle: String,
    val dailyQuotaSubtitle: String,
    val apiKeyTitle: String,
    val apiKeyPlaceholder: String,
    val saveApiKey: String
)

object AppStrings {
    private val spanish = AppTranslations(
        appName = "ZACK AI",
        menu = "Menú",
        newChat = "Nuevo Chat",
        close = "Cerrar",
        delete = "Eliminar",
        cancel = "Cancelar",
        yes = "Sí, por favor",
        notNow = "Ahora no",
        remindMe = "Recordármelo",
        ignore = "Ignorar",
        today = "Hoy",
        yesterday = "Ayer",
        previousDays = "Días anteriores",

        toolsHeader = "HERRAMIENTAS",
        cameraLens = "Cámara en Tiempo Real",
        shoppingList = "Lista de Compras",
        docTools = "Herramientas de Documentos",
        webBrowser = "Navegador Web IA",
        tasks = "Tareas y Recordatorios",
        modes = "MODO DE ASISTENTE",
        changeMode = "Cambiar",

        noChats = "No hay conversaciones aún",
        clearHistory = "Borrar todo el historial",
        deleteChatDialogTitle = "Eliminar conversación",
        deleteChatConfirm = "¿Estás seguro de que deseas eliminar este chat? Esta acción no se puede deshacer.",
        clearAllChatsDialogTitle = "Borrar todo el historial",
        clearAllChatsConfirm = "¿Deseas eliminar todas las conversaciones? Se borrarán permanentemente.",
        clearAllChatsConfirmBtn = "Borrar todo",

        quickSuggestions = "Sugerencias de inicio rápido:",
        chatPlaceholder = "Escribe o sube PDF, Word, Excel, PPT...",
        send = "Enviar",
        sendAudio = "Enviar Audio",
        dictate = "Dictar texto",
        speechPrompt = "Habla ahora...",
        recordingVoice = "Grabando voz...",
        cancelRecording = "Cancelar grabación",

        settingsTitle = "Ajustes",
        settingsSubtitle = "Configuración de tu Asistente Personal",
        languageSection = "Idioma de la App y de la IA",
        languageSubtitle = "Cambia los textos de la interfaz y el idioma con el que responde la IA.",
        modelsButton = "Modelos IA",
        modelsSubtitle = "Gemini 2.5 Flash activo con soporte multilingüe",
        appearanceSection = "Apariencia",
        appearanceSubtitle = "Tema visual de la interfaz",
        darkMode = "Oscuro",
        lightMode = "Claro",
        systemMode = "Sistema",
        voiceTypeSection = "Voz de Lectura",
        voiceTypeSubtitle = "Voz para reproducir las respuestas en voz alta",
        femaleVoice = "Femenina",
        maleVoice = "Masculina",
        dailyQuotaTitle = "Cuota de Consultas Diarias",
        dailyQuotaSubtitle = "Consultas gratuitas ilimitadas",
        apiKeyTitle = "Clave de API de Gemini",
        apiKeyPlaceholder = "Pega tu clave de API aquí...",
        saveApiKey = "Guardar Clave"
    )

    private val english = AppTranslations(
        appName = "ZACK AI",
        menu = "Menu",
        newChat = "New Chat",
        close = "Close",
        delete = "Delete",
        cancel = "Cancel",
        yes = "Yes, please",
        notNow = "Not now",
        remindMe = "Remind me",
        ignore = "Dismiss",
        today = "Today",
        yesterday = "Yesterday",
        previousDays = "Previous days",

        toolsHeader = "TOOLS",
        cameraLens = "Real-Time Camera",
        shoppingList = "Shopping List",
        docTools = "Document Tools",
        webBrowser = "AI Web Browser",
        tasks = "Tasks & Reminders",
        modes = "ASSISTANT MODE",
        changeMode = "Change",

        noChats = "No conversations yet",
        clearHistory = "Clear chat history",
        deleteChatDialogTitle = "Delete conversation",
        deleteChatConfirm = "Are you sure you want to delete this chat? This action cannot be undone.",
        clearAllChatsDialogTitle = "Clear all history",
        clearAllChatsConfirm = "Do you want to delete all conversations permanently?",
        clearAllChatsConfirmBtn = "Clear all",

        quickSuggestions = "Quick start suggestions:",
        chatPlaceholder = "Type or upload PDF, Word, Excel, PPT...",
        send = "Send",
        sendAudio = "Send Audio",
        dictate = "Dictate text",
        speechPrompt = "Speak now...",
        recordingVoice = "Recording voice...",
        cancelRecording = "Cancel recording",

        settingsTitle = "Settings",
        settingsSubtitle = "Personal Assistant Settings",
        languageSection = "App & AI Language",
        languageSubtitle = "Change interface language and AI response language.",
        modelsButton = "AI Models",
        modelsSubtitle = "Gemini 2.5 Flash active with multilingual support",
        appearanceSection = "Appearance",
        appearanceSubtitle = "Interface visual theme",
        darkMode = "Dark",
        lightMode = "Light",
        systemMode = "System",
        voiceTypeSection = "Reading Voice",
        voiceTypeSubtitle = "Voice to read aloud the responses",
        femaleVoice = "Female",
        maleVoice = "Male",
        dailyQuotaTitle = "Daily Query Quota",
        dailyQuotaSubtitle = "Unlimited free queries",
        apiKeyTitle = "Gemini API Key",
        apiKeyPlaceholder = "Paste your API key here...",
        saveApiKey = "Save Key"
    )

    private val french = AppTranslations(
        appName = "ZACK AI",
        menu = "Menu",
        newChat = "Nouveau Chat",
        close = "Fermer",
        delete = "Supprimer",
        cancel = "Annuler",
        yes = "Oui, s'il vous plaît",
        notNow = "Pas maintenant",
        remindMe = "Me le rappeler",
        ignore = "Ignorer",
        today = "Aujourd'hui",
        yesterday = "Hier",
        previousDays = "Jours précédents",

        toolsHeader = "OUTILS",
        cameraLens = "Caméra en Temps Réel",
        shoppingList = "Liste de Courses",
        docTools = "Outils Documentaires",
        webBrowser = "Navigateur Web IA",
        tasks = "Tâches et Rappels",
        modes = "MODE ASSISTANT",
        changeMode = "Changer",

        noChats = "Pas encore de conversations",
        clearHistory = "Effacer l'historique",
        deleteChatDialogTitle = "Supprimer la conversation",
        deleteChatConfirm = "Voulez-vous vraiment supprimer ce chat ? Cette action est irréversible.",
        clearAllChatsDialogTitle = "Effacer tout l'historique",
        clearAllChatsConfirm = "Voulez-vous supprimer définitivement toutes les conversations ?",
        clearAllChatsConfirmBtn = "Tout effacer",

        quickSuggestions = "Suggestions de démarrage rapide :",
        chatPlaceholder = "Écrivez ou importez PDF, Word, Excel, PPT...",
        send = "Envoyer",
        sendAudio = "Envoyer Audio",
        dictate = "Dicter du texte",
        speechPrompt = "Parlez maintenant...",
        recordingVoice = "Enregistrement vocal...",
        cancelRecording = "Annuler l'enregistrement",

        settingsTitle = "Paramètres",
        settingsSubtitle = "Configuration de votre Assistant Personnel",
        languageSection = "Langue de l'application et de l'IA",
        languageSubtitle = "Changez la langue de l'interface et des réponses de l'IA.",
        modelsButton = "Modèles IA",
        modelsSubtitle = "Gemini 2.5 Flash actif avec support multilingue",
        appearanceSection = "Apparence",
        appearanceSubtitle = "Thème visuel de l'interface",
        darkMode = "Sombre",
        lightMode = "Clair",
        systemMode = "Système",
        voiceTypeSection = "Voix de Lecture",
        voiceTypeSubtitle = "Voix pour la lecture vocale des réponses",
        femaleVoice = "Féminine",
        maleVoice = "Masculine",
        dailyQuotaTitle = "Quota de Requêtes Quotidiennes",
        dailyQuotaSubtitle = "Requêtes gratuites illimitées",
        apiKeyTitle = "Clé d'API Gemini",
        apiKeyPlaceholder = "Collez votre clé API ici...",
        saveApiKey = "Enregistrer la Clé"
    )

    private val portuguese = AppTranslations(
        appName = "ZACK AI",
        menu = "Menu",
        newChat = "Novo Chat",
        close = "Fechar",
        delete = "Excluir",
        cancel = "Cancelar",
        yes = "Sim, por favor",
        notNow = "Agora não",
        remindMe = "Lembrar-me",
        ignore = "Ignorar",
        today = "Hoje",
        yesterday = "Ontem",
        previousDays = "Dias anteriores",

        toolsHeader = "FERRAMENTAS",
        cameraLens = "Câmera em Tempo Real",
        shoppingList = "Lista de Compras",
        docTools = "Ferramentas de Documentos",
        webBrowser = "Navegador Web IA",
        tasks = "Tarefas e Lembretes",
        modes = "MODO DE ASSISTENTE",
        changeMode = "Mudar",

        noChats = "Nenhuma conversa ainda",
        clearHistory = "Limpar todo o histórico",
        deleteChatDialogTitle = "Excluir conversa",
        deleteChatConfirm = "Tem certeza de que deseja excluir este chat? Esta ação não pode ser desfeita.",
        clearAllChatsDialogTitle = "Limpar todo o histórico",
        clearAllChatsConfirm = "Deseja excluir permanentemente todas as conversas?",
        clearAllChatsConfirmBtn = "Limpar tudo",

        quickSuggestions = "Sugestões de início rápido:",
        chatPlaceholder = "Digite ou envie PDF, Word, Excel, PPT...",
        send = "Enviar",
        sendAudio = "Enviar Áudio",
        dictate = "Ditar texto",
        speechPrompt = "Fale agora...",
        recordingVoice = "Gravando voz...",
        cancelRecording = "Cancelar gravação",

        settingsTitle = "Configurações",
        settingsSubtitle = "Configurações do Assistente Pessoal",
        languageSection = "Idioma do App e da IA",
        languageSubtitle = "Altere o idioma da interface e das respostas da IA.",
        modelsButton = "Modelos de IA",
        modelsSubtitle = "Gemini 2.5 Flash ativo com suporte multilíngue",
        appearanceSection = "Aparência",
        appearanceSubtitle = "Tema visual da interface",
        darkMode = "Escuro",
        lightMode = "Claro",
        systemMode = "Sistema",
        voiceTypeSection = "Voz de Leitura",
        voiceTypeSubtitle = "Voz para ler as respostas em voz alta",
        femaleVoice = "Feminina",
        maleVoice = "Masculina",
        dailyQuotaTitle = "Cota Diária de Consultas",
        dailyQuotaSubtitle = "Consultas gratuitas ilimitadas",
        apiKeyTitle = "Chave de API do Gemini",
        apiKeyPlaceholder = "Cole sua chave de API aqui...",
        saveApiKey = "Salvar Chave"
    )

    private val german = AppTranslations(
        appName = "ZACK AI",
        menu = "Menü",
        newChat = "Neuer Chat",
        close = "Schließen",
        delete = "Löschen",
        cancel = "Abbrechen",
        yes = "Ja, bitte",
        notNow = "Jetzt nicht",
        remindMe = "Erinnere mich",
        ignore = "Ignorieren",
        today = "Heute",
        yesterday = "Gestern",
        previousDays = "Frühere Tage",

        toolsHeader = "WERKZEUGE",
        cameraLens = "Echtzeit-Kamera",
        shoppingList = "Einkaufsliste",
        docTools = "Dokumentwerkzeuge",
        webBrowser = "KI-Webbrowser",
        tasks = "Aufgaben & Erinnerungen",
        modes = "ASSISTENTENMODUS",
        changeMode = "Ändern",

        noChats = "Noch keine Unterhaltungen",
        clearHistory = "Gesamten Verlauf löschen",
        deleteChatDialogTitle = "Unterhaltung löschen",
        deleteChatConfirm = "Möchten Sie diesen Chat wirklich löschen? Dies kann nicht rückgängig gemacht werden.",
        clearAllChatsDialogTitle = "Gesamten Verlauf löschen",
        clearAllChatsConfirm = "Möchten Sie alle Unterhaltungen dauerhaft löschen?",
        clearAllChatsConfirmBtn = "Alles löschen",

        quickSuggestions = "Schnellstart-Vorschläge:",
        chatPlaceholder = "Schreiben oder PDF, Word, Excel, PPT hochladen...",
        send = "Senden",
        sendAudio = "Audio senden",
        dictate = "Text diktieren",
        speechPrompt = "Jetzt sprechen...",
        recordingVoice = "Sprachaufnahme...",
        cancelRecording = "Aufnahme abbrechen",

        settingsTitle = "Einstellungen",
        settingsSubtitle = "Persönliche Assistentenkonfiguration",
        languageSection = "App- und KI-Sprache",
        languageSubtitle = "Ändern Sie die Oberflächensprache und die KI-Antwortsprache.",
        modelsButton = "KI-Modelle",
        modelsSubtitle = "Gemini 2.5 Flash aktiv mit mehrsprachiger Unterstützung",
        appearanceSection = "Erscheinungsbild",
        appearanceSubtitle = "Visuelles Design der Oberfläche",
        darkMode = "Dunkel",
        lightMode = "Hell",
        systemMode = "System",
        voiceTypeSection = "Vorlesestimme",
        voiceTypeSubtitle = "Stimme zum Vorlesen von Antworten",
        femaleVoice = "Weiblich",
        maleVoice = "Männlich",
        dailyQuotaTitle = "Tägliche Abfragequote",
        dailyQuotaSubtitle = "Unbegrenzte kostenlose Abfragen",
        apiKeyTitle = "Gemini-API-Schlüssel",
        apiKeyPlaceholder = "Fügen Sie hier Ihren API-Schlüssel ein...",
        saveApiKey = "Schlüssel speichern"
    )

    private val italian = AppTranslations(
        appName = "ZACK AI",
        menu = "Menu",
        newChat = "Nuova Chat",
        close = "Chiudi",
        delete = "Elimina",
        cancel = "Annulla",
        yes = "Sì, grazie",
        notNow = "Non ora",
        remindMe = "Ricordamelo",
        ignore = "Ignora",
        today = "Oggi",
        yesterday = "Ieri",
        previousDays = "Giorni precedenti",

        toolsHeader = "STRUMENTI",
        cameraLens = "Fotocamera in Tempo Reale",
        shoppingList = "Lista della Spesa",
        docTools = "Strumenti Documenti",
        webBrowser = "Browser Web IA",
        tasks = "Attività e Promemoria",
        modes = "MODALITÀ ASSISTENTE",
        changeMode = "Cambia",

        noChats = "Nessuna conversazione",
        clearHistory = "Cancella tutta la cronologia",
        deleteChatDialogTitle = "Elimina conversazione",
        deleteChatConfirm = "Sei sicuro di voler eliminare questa chat? L'azione non può essere annullata.",
        clearAllChatsDialogTitle = "Cancella tutta la cronologia",
        clearAllChatsConfirm = "Vuoi eliminare definitivamente tutte le conversazioni?",
        clearAllChatsConfirmBtn = "Cancella tutto",

        quickSuggestions = "Suggerimenti di avvio rapido:",
        chatPlaceholder = "Scrivi o carica PDF, Word, Excel, PPT...",
        send = "Invia",
        sendAudio = "Invia Audio",
        dictate = "Detta testo",
        speechPrompt = "Parla ora...",
        recordingVoice = "Registrazione voce...",
        cancelRecording = "Annulla registrazione",

        settingsTitle = "Impostazioni",
        settingsSubtitle = "Configurazione dell'Assistente Personale",
        languageSection = "Lingua dell'App e dell'IA",
        languageSubtitle = "Modifica la lingua dell'interfaccia e delle risposte dell'IA.",
        modelsButton = "Modelli IA",
        modelsSubtitle = "Gemini 2.5 Flash attivo con supporto multilingue",
        appearanceSection = "Aspetto",
        appearanceSubtitle = "Tema visivo dell'interfaccia",
        darkMode = "Scuro",
        lightMode = "Chiaro",
        systemMode = "Sistema",
        voiceTypeSection = "Voce di Lettura",
        voiceTypeSubtitle = "Voce per ascoltare le risposte ad alta voce",
        femaleVoice = "Femminile",
        maleVoice = "Maschile",
        dailyQuotaTitle = "Quota Giornaliera di Richieste",
        dailyQuotaSubtitle = "Richieste gratuite illimitate",
        apiKeyTitle = "Chiave API Gemini",
        apiKeyPlaceholder = "Incolla qui la tua chiave API...",
        saveApiKey = "Salva Chiave"
    )

    fun get(languageCode: String): AppTranslations {
        return when (languageCode.lowercase()) {
            "en" -> english
            "fr" -> french
            "pt" -> portuguese
            "de" -> german
            "it" -> italian
            else -> spanish
        }
    }
}

val LocalAppStrings = staticCompositionLocalOf { AppStrings.get("es") }
val LocalAppLanguage = staticCompositionLocalOf { "es" }
